### ISSUE TITLE
Cannot compile on 2.0.0-1

### ISSUE THREAD

**Issue by Atlinx** [twinlogix/typetta#247]
Typetta doesn't compile, which prevents me from running my code.

```bash
node_modules/@twinlogix/typetta/lib/dal/dao/schemas/ast.types.d.ts:77:187 - error TS2344: Type 'P[K]' does not satisfy the constraint 'true | GraphQLResolveInfo | Projection<ASTName, AST> | undefined'.
  Type 'P[string] | P[number] | P[symbol]' is not assignable to type 'true | GraphQLResolveInfo | Projection<ASTName, AST> | undefined'.
    Type 'P[string]' is not assignable to type 'true | GraphQLResolveInfo | Projection<ASTName, AST> | undefined'.
      Type 'unknown' is not assignable to type 'true | GraphQLResolveInfo | Projection<ASTName, AST> | undefined'.
        Type 'unknown' is not assignable to type 'Projection<ASTName, AST>'.
          Type 'P[string]' is not assignable to type 'GraphQLResolveInfo'.
            Type 'P[K]' is not assignable to type 'GraphQLResolveInfo'.
              Type 'P[string] | P[number] | P[symbol]' is not assignable to type 'GraphQLResolveInfo'.
                Type 'P[string]' is not assignable to type 'GraphQLResolveInfo'.
                  Type 'unknown' is not assignable to type 'GraphQLResolveInfo'.

77     } ? ASTName extends string ? P[K] extends true ? Type extends 'scalar' ? Scalars[ASTName]['type'] : GenerateModel<ASTName, AST, Scalars, 'relation'> : Project<ASTName, AST, Scalars, P[K]> : never : never : never;
```

**Comment by edobrb** [comment]
The working one is [2.0.0-8](https://www.npmjs.com/package/@twinlogix/typetta/v/2.0.0-8). This version (2.0.0) contains a major typing rework and something is not backwards compatible (should be needed only some renames)

**Comment by Atlinx** [comment]
This still happens on 2.0.0-8

**Comment by edobrb** [comment]
You were right, can you try [2.0.0-9](https://www.npmjs.com/package/@twinlogix/typetta/v/2.0.0-9)?

**Comment by Atlinx** [comment]
Everything works with 2.0.0-9 😄
